In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import textacy.resources
import nltk

In [2]:
df2 = pd.read_csv('transcripts.csv')
rs = textacy.resources.DepecheMood(lang="en", word_rep="lemmapos")
transcript = list(df2['transcript'])
df2['transcript']

0       Good morning. How are you?(Laughter)It's been ...
1       Thank you so much, Chris. And it's truly a gre...
2       (Music: "The Sound of Silence," Simon & Garfun...
3       If you're here today — and I'm very happy that...
4       About 10 years ago, I took on the task to teac...
                              ...
2462    So, Ma was trying to explain something to me a...
2463    This is a picture of a sunset on Mars taken by...
2464    In my early days as a graduate student, I went...
2465    I took a cell phone and accidentally made myse...
2466    We humans are becoming an urban species, so ci...
Name: transcript, Length: 2467, dtype: object

In [7]:
sentiment = []
for i in range(0,len(transcript)):
    text = transcript[i]
    doc = textacy.make_spacy_doc(text, lang='en_core_web_sm')
    emo_dict = rs.get_emotional_valence(doc)
    emo_list = [emo_dict.get('AFRAID'),emo_dict.get('AMUSED'),emo_dict.get('ANGRY'),emo_dict.get('ANNOYED'),emo_dict.get('DONT_CARE'),emo_dict.get('HAPPY'),emo_dict.get('INSPIRED'),emo_dict.get('SAD')]
    sentiment.append(emo_list)
df = pd.DataFrame(data=sentiment,columns=['AFRAID','AMUSED','ANGRY','ANNOYED','DONT_CARE','HAPPY','INSPIRED','SAD'])
df

,AFRAID,AMUSED,ANGRY,ANNOYED,DONT_CARE,HAPPY,INSPIRED,SAD
0,0.092794,0.114177,0.116472,0.132365,0.129963,0.105839,0.201247,0.107143
1,0.108238,0.111975,0.121799,0.134885,0.129981,0.107100,0.178588,0.107434
2,0.093672,0.123894,0.115410,0.138560,0.138518,0.108802,0.179580,0.101564
3,0.105926,0.106197,0.128772,0.134356,0.121305,0.108597,0.182394,0.112452
4,0.108617,0.112215,0.118959,0.129735,0.126809,0.107173,0.184243,0.112248
...,...,...,...,...,...,...,...,...
2462,0.102343,0.108939,0.131899,0.138636,0.126494,0.101510,0.174694,0.115485
2463,0.120188,0.119194,0.114707,0.126044,0.117753,0.104346,0.175029,0.122739
2464,0.097120,0.131195,0.119608,0.129501,0.123598,0.106018,0.193803,0.099157
2465,0.094750,0.117907,0.122510,0.136626,0.131677,0.101304,0.191245,0.103982
2466,0.099718,0.114283,0.115306,0.133201,0.128464,0.111701,0.191686,0.105641

In [ ]:
df.to_csv('sentiment_score.csv',index=False)

In [3]:
df = pd.read_csv('sentiment_score.csv')
df

,AFRAID,AMUSED,ANGRY,ANNOYED,DONT_CARE,HAPPY,INSPIRED,SAD
0,0.092794,0.114177,0.116472,0.132365,0.129963,0.105839,0.201247,0.107143
1,0.108238,0.111975,0.121799,0.134885,0.129981,0.107100,0.178588,0.107434
2,0.093672,0.123894,0.115410,0.138560,0.138518,0.108802,0.179580,0.101564
3,0.105926,0.106197,0.128772,0.134356,0.121305,0.108597,0.182394,0.112452
4,0.108617,0.112215,0.118959,0.129735,0.126809,0.107173,0.184243,0.112248
...,...,...,...,...,...,...,...,...
2462,0.102343,0.108939,0.131899,0.138636,0.126494,0.101510,0.174694,0.115485
2463,0.120188,0.119194,0.114707,0.126044,0.117753,0.104346,0.175029,0.122739
2464,0.097120,0.131195,0.119608,0.129501,0.123598,0.106018,0.193803,0.099157
2465,0.094750,0.117907,0.122510,0.136626,0.131677,0.101304,0.191245,0.103982
2466,0.099718,0.114283,0.115306,0.133201,0.128464,0.111701,0.191686,0.105641

In [10]:
data = pd.concat([df2, df],axis=1,join= 'outer') 
data.to_csv('sentiment_tran.csv',index=False)

In [11]:
data

,transcript,url,AFRAID,AMUSED,ANGRY,ANNOYED,DONT_CARE,HAPPY,INSPIRED,SAD
0,Good morning. How are you?(Laughter)It's been ...,https://www.ted.com/talks/ken_robinson_says_sc...,0.092794,0.114177,0.116472,0.132365,0.129963,0.105839,0.201247,0.107143
1,"Thank you so much, Chris. And it's truly a gre...",https://www.ted.com/talks/al_gore_on_averting_...,0.108238,0.111975,0.121799,0.134885,0.129981,0.107100,0.178588,0.107434
2,"(Music: ""The Sound of Silence,"" Simon & Garfun...",https://www.ted.com/talks/david_pogue_says_sim...,0.093672,0.123894,0.115410,0.138560,0.138518,0.108802,0.179580,0.101564
3,If you're here today — and I'm very happy that...,https://www.ted.com/talks/majora_carter_s_tale...,0.105926,0.106197,0.128772,0.134356,0.121305,0.108597,0.182394,0.112452
4,"About 10 years ago, I took on the task to teac...",https://www.ted.com/talks/hans_rosling_shows_t...,0.108617,0.112215,0.118959,0.129735,0.126809,0.107173,0.184243,0.112248
...,...,...,...,...,...,...,...,...,...,...
2462,"So, Ma was trying to explain something to me a...",https://www.ted.com/talks/duarte_geraldino_wha...,0.102343,0.108939,0.131899,0.138636,0.126494,0.101510,0.174694,0.115485
2463,This is a picture of a sunset on Mars taken by...,https://www.ted.com/talks/armando_azua_bustos_...,0.120188,0.119194,0.114707,0.126044,0.117753,0.104346,0.175029,0.122739
2464,"In my early days as a graduate student, I went...",https://www.ted.com/talks/radhika_nagpal_what_...,0.097120,0.131195,0.119608,0.129501,0.123598,0.106018,0.193803,0.099157
2465,I took a cell phone and accidentally made myse...,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,0.094750,0.117907,0.122510,0.136626,0.131677,0.101304,0.191245,0.103982
2466,"We humans are becoming an urban species, so ci...",https://www.ted.com/talks/karoliina_korppoo_ho...,0.099718,0.114283,0.115306,0.133201,0.128464,0.111701,0.191686,0.105641

In [5]:
df3 = pd.read_csv('ted_main.csv')
df3

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2546,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2547,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2548,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2549,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [6]:
big_data = pd.merge(df3, data, on=['url', 'url'],how= 'inner') 
big_data

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,...,views,transcript,AFRAID,AMUSED,ANGRY,ANNOYED,DONT_CARE,HAPPY,INSPIRED,SAD
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,...,47227110,Good morning. How are you?(Laughter)It's been ...,0.092794,0.114177,0.116472,0.132365,0.129963,0.105839,0.201247,0.107143
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,...,3200520,"Thank you so much, Chris. And it's truly a gre...",0.108238,0.111975,0.121799,0.134885,0.129981,0.107100,0.178588,0.107434
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,...,1636292,"(Music: ""The Sound of Silence,"" Simon & Garfun...",0.093672,0.123894,0.115410,0.138560,0.138518,0.108802,0.179580,0.101564
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,...,1697550,If you're here today — and I'm very happy that...,0.105926,0.106197,0.128772,0.134356,0.121305,0.108597,0.182394,0.112452
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,...,12005869,"About 10 years ago, I took on the task to teac...",0.108617,0.112215,0.118959,0.129735,0.126809,0.107173,0.184243,0.112248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2462,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,...,450430,"So, Ma was trying to explain something to me a...",0.102343,0.108939,0.131899,0.138636,0.126494,0.101510,0.174694,0.115485
2463,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,...,417470,This is a picture of a sunset on Mars taken by...,0.120188,0.119194,0.114707,0.126044,0.117753,0.104346,0.175029,0.122739
2464,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,...,375647,"In my early days as a graduate student, I went...",0.097120,0.131195,0.119608,0.129501,0.123598,0.106018,0.193803,0.099157
2465,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,...,419309,I took a cell phone and accidentally made myse...,0.094750,0.117907,0.122510,0.136626,0.131677,0.101304,0.191245,0.103982
2466,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,...,391721,"We humans are becoming an urban species, so ci...",0.099718,0.114283,0.115306,0.133201,0.128464,0.111701,0.191686,0.105641

In [ ]:
big_data.to_csv('big_data.csv',index=False)